config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :users, only: [:show, :edit, :update] do                           # member => restaurant id in URL
    resources :reviews, only: [:index, :new, :create]
    resources :favorites, only: [:index]
  end

  resources :articles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :create, :edit, :update] do

  end


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end

  resources :tags, only: [:show]

  namespace :sellers do
    resources :orders, only: :update
  end

  namespace :buyers do
    resources :orders, only: :update
  end

  get :autocomplete, to: 'pages#autocomplete'
  get "dashboard", to: 'pages#dashboard'
  get "listings", to: 'pages#listings'
  get "about", to: 'pages#about'
  get "shop", to: 'articles#index'

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_article, except: :index

  def index
    @favorites = policy_scope(Favorite.all)
    @user = User.find(params[:user_id])
  end

  def create
    @favorite = Favorite.new(user: current_user, article: @article)
    authorize @favorite
    if @favorite.save
      respond_to do |format|
        format.html { redirect_to articles_path }

        format.js
      end
    else
      respond_to do |format|

        format.html { render 'articles/index' }
        format.js  # <-- idem

      end
    end
  end

  def destroy
    @favorite = Favorite.where(user: current_user, article: @article).first

    authorize @favorite
    @favorite.destroy
    # redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:article_id])
  end
end

app/views/favorites/_toggle_favorite_action.html.erb
<% if user&.has_favorited?(article) %>
  <%= link_to article_favorite_path(article, user.get_favorite(article)), method: :delete,  remote: true, class: 'article-star', id: "article-#{article.id}" do %>
    <% if current_user %>
    <i class="fas fa-star white fa-lg"></i>
    <% end %>
  <% end %>
<% elsif policy(Favorite).create? %>
  <%= link_to article_favorites_path(article), method: :post,  remote: true, id: "article-#{article.id}", class: 'article-star' do %>
     <% if current_user %>
    <i class="far fa-star white fa-lg"></i>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
function addToFavorites() {
  var star = document.querySelector(`#action-article-<%= @favorite.article.id %>`);
  star.innerHTML = '<%= j render "toggle_favorite_action", article: @favorite.article, user: current_user %>' ;
}

addToFavorites();

app/views/favorites/destroy.js.erb
function removeFromFavorites() {
  var star = document.querySelector(`#action-article-<%= @favorite.article.id %>`);
  star.innerHTML = '<%= j render "toggle_favorite_action", article: @favorite.article, user: current_user %>';
}

removeFromFavorites();

app/views/favorites/index.html.erb
<div class="background-profile">

</div>
<div class="backround-user">
  <div class="profile-info">
    <% if @user.photo.attached? %>
      <%= cl_image_tag @user.photo.key, class: "avatar-xl", alt: "profile picture" %>
    <% elsif @user == current_user %>
      <%= link_to edit_user_path(current_user) do %>
        <%= image_tag "avatar.png", class: "avatar-xl" %>
      <% end %>
    <% else %>
      <%= image_tag "avatar.png", class: "avatar-xl" %>
    <% end %>
  <h2><%=  @user&.name%></h2>
   <p>
    <% @user.rating.times do %>
     ⭐
    <% end %>
  </p>
  <p>madrid, spain</p>
  </div>
<div class="profile-links">

  <div class= "clothes-color-2">
    <%= link_to "clothes", user_path(@user)%>
  </div>
  <div class="clothes">
    <%= link_to "likes", user_favorites_path(@user)%>
  </div>
  <% if  @user.articles%>
  <div class="likes">
    <%= link_to "reviews", user_reviews_path(@user)%>
  </div>
  <% end %>
</div>

</div>

<div class="clothing-grid">
  <% @favorites.each do |favorite| %>
    <%= link_to article_path(favorite.article) do %>
      <% if favorite.article.photos.first.nil?  %>
        <%= image_tag 'default-article.png', class: "article-photo" %>
      <% else  %>
        <%= cl_image_tag favorite.article.photos.first.key, class: "article-photo" %>
      <% end %>
    <% end %>
  <% end %>
</div>