config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :users, only: [:show, :edit, :update] do                           # member => restaurant id in URL
    resources :reviews, only: [:index, :new, :create]
    resources :favorites, only: [:index]
  end

  resources :articles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :create, :edit, :update] do

  end


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end

  resources :tags, only: [:show]

  namespace :sellers do
    resources :orders, only: :update
  end

  namespace :buyers do
    resources :orders, only: :update
  end

  get :autocomplete, to: 'pages#autocomplete'
  get "dashboard", to: 'pages#dashboard'
  get "listings", to: 'pages#listings'
  get "about", to: 'pages#about'
  get "shop", to: 'articles#index'

end

app/models/article.rb
class Article < ApplicationRecord
   include Rails.application.routes.url_helpers
  belongs_to :category
  belongs_to :user

  has_many :orders

  has_many :article_tags
  has_many :tags, through: :article_tags

  has_many_attached :photos

  monetize :price_cents

  validates :photos, presence: true

  validates :name, presence: true
  validates :name, presence: true
  validates :price_cents, presence: true
  has_many :favorites, dependent: :destroy

  scope :with_tags, -> (tag_names) do
    Article.joins(:tags).where(tags: { name: tag_names } )
  end

  scope :favorited_by, -> (username) { joins(:favorites).where(favorites: { user: User.where(username: username) }) }

  scope :available, -> do
    includes(:orders).where(orders: { id: nil })
                     .or(Article.with_cancelled_orders)
  end

  scope :with_pending_orders, -> do
    includes(:orders).where(orders: { state: 'pending' })
  end

  scope :with_paid_orders, -> do
    includes(:orders).where(orders: { state: 'paid' })
  end

  scope :with_shipped_orders, -> do
    includes(:orders).where(orders: { state: 'shipped' })
  end

  scope :with_delivered_orders, -> do
    includes(:orders).where(orders: { state: 'delivered' })
  end

  scope :with_cancelled_orders, -> do
    includes(:orders).where(orders: { state: 'cancelled' })
  end

  def self.available_colors
    pluck(:color).reject(&:nil?).uniq
  end

  def self.available_size
    pluck(:size).reject(&:nil?).uniq
  end

  ransacker :price_money, type: :integer, formatter: proc { |dollars| dollars * 100 } do |p|
    p.table[:price_cents]
  end

  include PgSearch::Model
  pg_search_scope :search_by_name_and_color_and_material_and_category,
  # <-- I am not sure if it is OK to put category_id as it refers to another table

    against: [ :name, :color, :material],
    using: {
      tsearch: { prefix: true }     },
    associated_against: {
      category: [:name],
      tags: [:name]
    }

  def active_orders?
    orders.active.any?
  end

  def active_order
    orders.active.first
  end

  def image_url
    return nil unless photos.any?

    rails_blob_url(photos.first, Rails.application.config.action_mailer.default_url_options)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]



  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).includes(:category, :tags)
    if params[:q_search].present?
      @pg_result = Article.search_by_name_and_color_and_material_and_category(params[:q_search])
    end

    @articles = policy_scope(@articles).order(created_at: :desc)
                                          .with_attached_photos
    @articles = @articles & @pg_result if @pg_result

    if current_user
      @articles  = @articles - current_user.articles
    end
    @favorite = Favorite.new
  end

  def show
    @order = Order.new
    @tags = Tag.all

    authorize @article

    @user_articles = @article.user
                             .articles
                             .with_attached_photos
  end


  def new
    @article = Article.new
    authorize @article
  end


  def edit
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end


  def update
    authorize @article
      if @article.update(article_params)
         redirect_to article_path(@article) # notice: 'Restaurant was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @article.destroy
  end

  private

    def set_article
      @article = Article.with_attached_photos.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name, :category_id, :color, :size, :material, :shipping_cost, :user_id, :description, :state, :price_cents, photos: [])
    end


end

app/views/articles/_article.html.erb
<div class="article-container">
  <% if article.photos.first.nil?  %>
    <div class="article-card" style="background-image: url(<%= image_path 'default-article.png' %>);">
    </div>
  <% else  %>
    <div class="article-card" style="background-image: url(<%= cl_image_path article.photos.first.key %>);">
    </div>
  <% end %>

  <div class="article-card-infos">
    <h3><%= article.name%></h3>
    <h4><%= humanized_money_with_symbol article.price %></h4>
  </div>
  <div id="action-<%= "article-#{article.id}" %>">
    <%= render "favorites/toggle_favorite_action", user: current_user, article: article %>
  </div>
  <%= link_to '', article_path(article), class: 'article-card-link' %>
</div>

app/views/articles/_article_photo.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval= "false" data-touch= "true">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @article.photos.first.nil?  %>
        <%= image_tag 'default-article.png', style:"width: 100%;" %>
      <% else  %>
       <%= cl_image_tag @article.photos.first.key, style:"width: 100%;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_article_photos.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval= "false" data-touch= "true">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
  </ol>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @article.photos.first.nil?  %>
        <%= image_tag 'default-article.png', style:"width: 100%;" %>
      <% else  %>
       <%= cl_image_tag @article.photos.first.key, style:"width: 100%;" %>
      <% end %>
    </div>
    <%  @article.photos.each_with_index do |photo, i| %>
      <% unless i == 0 %>
        <div class="carousel-item">
          <%= cl_image_tag photo.key, style:"width: 100%;" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/articles/_form.html.erb
<div class="form-container">
<%= simple_form_for(article) do |f| %>

<div class="form-inputs">
<%= f.input :name, label: "Title", placeholder: 'Cute top', :input_html => { :class => "text" } %>
<%= f.input :size, label: "Size ", placeholder: 'S/M/L' , :input_html => { :class => "text" } %>
<%= f.input :material, label: "Fabric ", placeholder: 'Fabric', :input_html => { :class => "text" } %>
<%= f.input :state, label: "State", placeholder: 'Lightly worn', :input_html => { :class => "text" } %>
<%= f.input :price_cents, label: "List Price", placeholder: '$75.00', :input_html => { :class => "text" } %>
<%= f.association :category %>
<%= f.input :description, label: "Description", placeholder: 'Leather suit', :input_html => { :class => "text" } %>
<%= f.input :photos, as: :file, input_html: { multiple: true } %>
<%= f.input :shipping_costs, label: "Shipping Cost ", placeholder: '$10.00' %>
<%#= f.button :submit,  "List", class: "mainbutton"%>
</div>

<%= f.button :submit,  "List", class: "btn coral-button", style: "margin-bottom: 10px;" %>

<% end %>
</div>

app/views/articles/edit.html.erb
<h2>Edit an article</h2>
<%=  render "form", article: @article %>

app/views/articles/index.html.erb
<% content_for :meta_title, "Explore cool festival outfits" %>


<div class="page-container">
  <div class="banner-index">
    <div class="header-index">
      <h1>shop</h1>
      <h1>fancier</h1>
    </div>

  </div>

  <div class="search-index">
    <%= form_tag(articles_path, method: 'get', class: "form-inline") do %>
    <div id= "search-data" class="form-search search-data" data-articles="<%= @articles.to_json %>">
      <%= text_field_tag :q_search, nil, autocomplete: :off, class: "form-control search-input", placeholder: "Search" %>
    </div>
    <% end %>
  </div>


  <div class="category-name">
    <h1>Shop All</h1>
    <p id= "viewall"><%= link_to "view all", articles_path %></p>
  </div>


  <div class="article-cards-container">
    <% @articles.each do |article| %>
    <%= render article %>
    <% end %>
  </div>



  <!-- Button trigger modal -->
  <button type="button" class="btn filter-button" data-toggle="modal" data-target="#exampleModalLong">
    <i class="fas fa-filter"></i>
   <%#= image_tag "icon-filter-8.png", style: "width:14px;" %>
   &nbsp; filter
 </button>

 <!-- Modal -->
 <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true" style="border-radius: 5px;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title title-style" id="exampleModalLongTitle" style= "font-weight: bold;">Filter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= search_form_for @q do |f| %>
      <h5 class="modal-title title-style" id="exampleModalLongTitle">Choose a Category</h5>
      <div class="modal-body">
        <section class="category">
        <%= f.select :category_name_eq,
          options_for_select(Category.all.map{|x| x.name}),
          {include_blank: "Category", class: 'filter-select'}
        %>
        </section>
      </div>
      <h5 class="modal-title title-style" id="exampleModalLongTitle">Color</h5>
      <div class="modal-body">
       <section class="colors">
          <%= f.select :color_eq,
          options_for_select(Article.available_colors.map{|a| [a.capitalize, a]}),
          {include_blank: "Color", class: 'filter-select'} %>
        </section>
      </div>
    <h5 class="modal-title title-style" id="exampleModalLongTitle">Size</h5>
    <div class="modal-body">
      <section class="size">
        <%= f.select :size_eq, options_for_select(Article.available_size.map{|a| [a.upcase, a]}), {include_blank: "Size", class: 'filter-select'} %>
      </section>

    </div>
    <h5 class="modal-title title-style" id="exampleModalLongTitle">Max Price</h5>
    <div class="modal-body">

      <%= f.number_field :price_money_lteq, class: "outside-view" %>
      <div class="d-flex justify-content-between">
         <p style= "font-size: 12px; color: #171717; margin-right: 4px;"> $0 </p>
       <input type ="range" max="300" min="0"
        oninput="document.getElementById('rangeValLabel').innerHTML = this.value;"
        step="1" name="rangeVal" id="money-slider" class= "slider" value="150">
        </input> <p style= "font-size: 12px; color: #171717;; margin-left: 4px">$300</p>
      </div>

      <div class="d-flex justify-content-center">
      <p style= "font-size: 12px; color: #171717;">$</p>
      <em id="rangeValLabel" style="font-style: normal; color: #171717; display: flex; justify-content: center;">150</em>
      </div>
   </div>
   <h5 class="modal-title title-style" id="exampleModalLongTitle">Choose a vibe</h5>
   <div class="modal-body">
    <section>
    <%= f.select :tags_name, options_for_select(Tag.all.map(&:name)), {include_blank: "Vibes"} %>
    </section>
  </div>

  <div class="modal-footer">
<%= f.submit "search", class: "btn coral-button" %>
  </div>
  <% end %>
</div>
</div>
</div>





<!-- After executed search back to index -->

<div class=search-footer>

  <% if params[:query] %>
    <%= link_to "Back to Overview", articles_path, class: 'btn btn-primary' %>
  <% end %>
</div>
</div>

app/views/articles/new.html.erb
<div class="new-article-container">
<div class="form-header">
  <h2>Sell an article</h2>
</div>
<%=  render "form", article: @article %>

</div>

app/views/articles/show.html.erb
<% content_for :meta_title, "Buy #{@article.name} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @article.description %>
<%# content_for :meta_image, cl_image_path(@article.photo.path) %>


<% if @article.photos.first.nil?  %>
  <%= image_tag 'default-article.png', style:"width: 100%;", data: {toggle:"modal", target: "#exampleModalCenter"}%>
<% else  %>
  <%= cl_image_tag @article.photos.first.key, style:"width: 100%;", data: {toggle:"modal", target: "#exampleModalCenter"}%>
<% end %>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content container">
      <div class="modal-body">
        <%= render (@article.photos.size == 1 ? 'article_photo' : 'article_photos') %>
      </div>
    </div>
  </div>
</div>



<div class=" info">
  <p style= "text-align: center; font-size: 12px;">Click image to view fullscreen</p>
  <%#= link_to edit_article_path do %>
  <!-- <i class="far fa-edit edit"></i> -->
  <%# end %>
  <div>
    <div class="d-flex justify-content-start" style="margin: 10px">
      <%# if user_signed_in? %>
      <%= link_to user_path(@article.user) do %>
      <% if @article.user.photo.attached? %>
        <%= cl_image_tag @article.user.photo.key, class: "avatar" %>
      <% else %>
        <%= image_tag "avatar.png", class: "avatar" %>
      <% end %>
      <% end %>
      <%# end %>
      <div class="profile-tag">
        <p class="bold"> <%= @article.user&.name %> </p>
        <!-- <p>madrid, spain</p> -->
        <p>⭐⭐⭐⭐⭐
          <%# @article.user.rating.times do %>

          <%# end %>
        </p>
      </div>
    </div>
    <div class= "d-flex justify-content-between">
      <div>
        <h5 style= "font-weight: bold"> <%= @article.name %>
          <%#= @article.category.name %></h5>
        </div>
        <p style= "font-weight: bold"> <%= humanized_money_with_symbol @article.price %> </p>
      </div>
      <p>SIZE: <%= @article.size %> </p>
      <p> <%= @article.description&.truncate_words(25)%> </p>
      <% unless @article.user == current_user %>
      <button type="button" class="btn coral-button btn-lg" data-toggle="modal" data-target="#myModal2">
        add to cart
      </button>
      <% end %>
    </div>

    <!-- Modal -->
    <div class="modal right fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" data-backdrop="false">
      <div class="modal-dialog" role="document">
        <div class="modal-content">

          <div class="modal-header">
           <h4 class="modal-title" id="myModalLabel2" style="letter-spacing: 2px; color: #1F2023;">BAG</h4>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         </div>

         <div class="modal-body">
          <div class="d-flex">
            <% if @article.photos.first.nil?  %>
              <%= image_tag 'default-article.png', style:"width: 140px; height: 100%;" %>
            <% else  %>
             <%= cl_image_tag @article.photos.first.key, style:"width: 140px; height: 100%;" %>
            <% end %>

            <div class= "side-info">
              <h5 style= "font-weight: bold"><%= @article.name %>
                </h5>
                <p>SIZE: <%= @article.size&.upcase %></p>
                <p><%= humanized_money_with_symbol @article.price %></p>
              </div>
            </div>

            <hr>
            <div class="d-flex justify-content-between">
              <p>SUBTOTAL</p>
              <p><%= humanized_money_with_symbol @article.price %></p>
            </div>

            <%= simple_form_for @order do |f|%>
            <%= f.input :name %>
            <%= f.input :street_address %>
            <%= f.input :apartment_number %>
            <%= f.input :city %>
            <%= f.input :state_address, label: "State" %>
            <%= f.input :postal_code %>
            <%= f.country_select :country, {include_blank: 'Select a country'}, {class: 'form-control'}%>
            <%= f.input :article_id, :as => :hidden, :input_html => { :value => @article.id } %>
            <%= f.submit 'checkout', class: 'btn coral-button btn-lg' %>
            <% end %>

          </div>

        </div><!-- modal-content -->
      </div><!-- modal-dialog -->
    </div><!-- modal -->

  </div><!-- container -->

  <div class="container clothes-seller change-font">
  <% unless @article.user == current_user %>
    <h2>You might also like...</h2>
      <% if @article.user.articles.count > 1 %>
        <% @article.user.articles.each do |article| %>
          <% unless article == @article %>
            <%= link_to article_path(article) do %>
              <% if @article.photos.first.nil?  %>
                <%= image_tag 'default-article.png', style:" seller-article" %>
              <% else  %>

               <%= cl_image_tag article.photos.first.key, class: "seller-article" %>
              <% end %>
            <% end %>
          <% end %>
          <% end %>

        <% else %>


        <% Article.with_tags(@article.tags.pluck(:name)).each do |article| %>
          <% unless article == @article %>
            <%= link_to article_path(article) do %>
              <% if @article.photos.first.nil?  %>
                <%= image_tag 'default-article.png', class: " seller-article" %>
              <% else  %>
                <%= cl_image_tag article.photos.first.key, class: " seller-article" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
   <% end %>
  </div>