config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :users, only: [:show, :edit, :update] do                           # member => restaurant id in URL
    resources :reviews, only: [:index, :new, :create]
    resources :favorites, only: [:index]
  end

  resources :articles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :create, :edit, :update] do

  end


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end

  resources :tags, only: [:show]

  namespace :sellers do
    resources :orders, only: :update
  end

  namespace :buyers do
    resources :orders, only: :update
  end

  get :autocomplete, to: 'pages#autocomplete'
  get "dashboard", to: 'pages#dashboard'
  get "listings", to: 'pages#listings'
  get "about", to: 'pages#about'
  get "shop", to: 'articles#index'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <% if controller_name == "articles" && action_name == "show" %>
      <%= link_to :back do  %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
    <% else %>
      <div class="nav-toggle">
        <i class="fas fa-bars"></i>
      </div>
  <% end %>

  <%= link_to root_path do %>
    <%= image_tag "logo2.png" %>
  <% end %>
  <!-- <h3 id="logo"> <%#= link_to "fancier.", root_path %> </h3> -->
  <%= link_to articles_path do %>
    <i class="fas fa-shopping-bag"></i>
  <% end %>
</div>
<nav class="nav style-nav nav-hidden">
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sell", new_article_path %></li>
    <li><%= link_to "Shop", articles_path %></li>

    <% if user_signed_in? %>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "My Orders", dashboard_path %></li>
    <% end %>


    <hr>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Login", new_user_session_path %>
      </li>

    <% end %>
  </ul>
</nav>