config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  resources :users, only: [:show, :edit, :update] do                           # member => restaurant id in URL
    resources :reviews, only: [:index, :new, :create]
    resources :favorites, only: [:index]
  end

  resources :articles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :favorites, only: [:create, :destroy]
  end
  resources :orders, only: [:show, :create, :edit, :update] do

  end


  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
    resources :reviews, only: [:new, :create]
  end

  resources :tags, only: [:show]

  namespace :sellers do
    resources :orders, only: :update
  end

  namespace :buyers do
    resources :orders, only: :update
  end

  get :autocomplete, to: 'pages#autocomplete'
  get "dashboard", to: 'pages#dashboard'
  get "listings", to: 'pages#listings'
  get "about", to: 'pages#about'
  get "shop", to: 'articles#index'

end

app/views/pages/about.html.erb
<div class="page-about-container">

  <div class="body-container">
  <h1><strong>what is fancier?</strong></h1>

<div id="header-section">



<div class="body-text">
<h2>hi welcome to fancier!</h2>
<p>Fancier is a global community of creative people who like to shine and express themselves. We are the first online marketplace specialized in vintage festival outfits, custom-made disguises, and original cosplay styles.</p>
<p>From Burning Man to Coachella, Tomorrow Land or your very own Halloween Party - we've got you covered. We believe that looking fancy doesn't have to involve big budgets or shopping fast fashion.</p>
<p>The fashion industry is one of the biggest threads to the global climate. Reducing, reducing and recycling by buying vintage is a solid way to make a positive impact.</p>
</div>
</div>
</div>

<div class="image-background">
  <h3>We’re a global community of movers, shakers and self-expressers who change the rules of fashion.</h3>
  <% link_to "join the crew", new_user_session_path, class: "" %>
</div>

<!-- <div class="body-container">

<div class="quote-section">
  <h4>Sharing is caring. At Fancier, we help you find the best outfits as well as selling it when the party is over.</h4>
  <h5>-Fancier Team</h5>
</div>

</div> -->


</div>

app/views/pages/dashboard.html.erb
<div class="background-profile">

</div>
<div class="backround-user">

  <div class="profile-info">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar-xl", alt: "profile picture" %>
    <% else %>
      <%= image_tag "avatar.png", class: "avatar-xl" %>
    <% end %>

    <div class="add-margin">
      <h2>Order Dashboard</h2>
    </div>
  </div>
  <div class="dashboard-links">
    <div class="clothes">
      <a href="/dashboard">my purchases</a>
    </div>
    <div class="likes">
      <a href="/listings">my listings</a>
    </div>
  </div>
</div>


<div class="order-container">

  <div class="order-section">
    <div class="orders">
      <% current_user.orders.each do |order| %>
        <div class="d-flex border-order">
          <% if order.article.photos.first.nil?  %>
            <div class="order-photo" style="background-image:url(<%= image_path 'default-article.png' %>);">
            </div>
          <% else  %>

            <%= link_to article_path(order.article) do %>
            <div class="order-photo" style="background-image:url(<%= cl_image_path order.article.photos.first.key %>);">
            </div>
            <% end %>
          <% end %>
          <div class="order-info">

            <h2><%= order.article.name.capitalize %></h2>

            <h3>SIZE: <%= order.article.size %></h3>
            <h4><%= humanized_money_with_symbol order.article.price %></h4>
            <% if order.state != 'shipped' %>
            <p><%= order.state%></p>
            <% end %>

            <% if order.state == 'shipped' %>
              <div class="margin-button">
                <%= link_to " Mark as received", buyers_order_path(order), method: :patch, class: 'received' %>
             </div>


             <div class="d-flex photo-change margin-top-dash mt-20">
              <% if order.article.user.photo.attached? %>
                <%= cl_image_tag order.article.user.photo.key, class: "avatar-xsmall" %>

              <% else %>
                <%= image_tag "avatar.png", class: "avatar-xsmall" %>
              <% end %>
              <h4 class="" style= "font-weight: 400; "><%=  order.article.user&.name %> has shipped this item!</h4>
            </div>



            <% elsif order.state == "delivered" && order.review.nil? %>
              <%= link_to "Review the seller", new_order_review_path(order), class: "review-button" %>
            <% end %>
          </div>
        </div>
        <div class="total-section justify-content-between">
          <div class="subtotal">SUBTOTAL</div>
          <div class="price"><%= humanized_money_with_symbol order.article.price %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class ="background-mobile">
  <%=  image_tag("xfancier.png", class: "iphone") %>
  <div class="mobile-header">
    <h1>Welcome to Fancier!</h1>
    <p>Fancier is currently optimized for mobile browsing. Feel free to open the website on your phone with the QR code below.</p>
    <%=  image_tag("qrcode.svg", class: "qr") %>
  </div>
</div>



<div class="home-styling">

<div class="main-container">
  <div class="main-text">
    <h1 class="hp">share the glitter, not the litter</h1>
    <p>#1 destination for unique festival outfits and costumes</p>
     <div class="sell-button margin-change">
      <%= link_to "shop all", articles_path, class: 'content-button-photo' %>
    </div>
   <!--  <p class="hp">Fancy, freaky, funky, cheeky - you name it, we have it.
    Fancier is your number one destination for festival outfits and custom-made costumes.
    From Comicon to Burning Man, time to get sassy!
    </p> -->
    <!-- <p>#1 destination to find your unique festival outfit</p> -->
    <%#= link_to " explore", articles_path, class: 'mainbutton' %>
  </div>
</div>

<!-- <div class="video-overlay"></div>
<%#= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "sparkle_video" %>
<div class="page-container"> -->


<div class="content-container-text">
  <div class="content-text change-spacing">
    <h1> <strong>got festival tickets</strong> </h1>
    <h1> <strong>but nothing to</strong></h1>
    <h1> <strong> wear?</strong></h1>
    <!-- <p>#1 destination to find your unique festival outfit</p> -->

    <div class="cta">
      <%= link_to "shop", articles_path %>
      <i class="fas fa-chevron-right"></i>
    </div>
  </div>
</div>


<div class="content-container-text add-photo">
  <div class="content-text-photo spacing-change change-spacing">
    <h1 class="hp">made a sick outfit but got nowhere to sell it?</h1>
    <!-- <p>#1 destination to find your unique festival outfit</p> -->
    <div class="sell-button">
      <%= link_to "sell on fancier", new_article_path, class: 'content-button-photo' %>
    </div>
  </div>
</div>


<div class="content-container-text">
  <div class="content-text down-spacing">
    <h1> <strong> fast fashion ain't</strong></h1>
    <h1> <strong> your thang? </strong></h1>
    <!-- <p>#1 destination to find your unique festival outfit</p> -->
    <div class="cta">
        <%= link_to "about", about_path, class: '' %>
        <i class="fas fa-chevron-right"></i>
    </div>
  </div>
</div>

<div class="content-container-photo2">
  <div class="content-text-photo">
    <h6>GET INSPIRED</h6>
    <h1 class="hp">Burning Man</h1>
    <!-- <p>#1 destination to find your unique festival outfit</p> -->
    <div class="sell-button">
      <%= link_to "browse", tag_path(@tags.first), class: "content-button"%>
    </div>
  </div>
</div>

<div class="content-wrapper">
  <div class="text-container">
    <h1>Join the crew</h1>
    <h3> We’re a global community of movers, shakers and self-expressers who change the rules of fashion.</h3>
      <div class="sell-button-2">
        <%= link_to "sign up now", new_user_session_path, class: 'content-button-photo' %>
        </div>
      </div>
</div>

<!-- <div class="tags-container-new">
    <div class="tag-cards-new">
      <#% @tags.each do |tag| %>
      <%#= link_to tags_path(name: tag.name) do %>
        <div class="tag-image-new" style="background-image: asset-url('girls.png')">
           <p>
            <%#= tag.name.pluralize %>
           </p>
        </div>
        <%# end %>
      <#% end %>
  </div> -->




<!-- <div class="content-container-photo2">
  <div class="content-text-photo">
    <h6>GET INSPIRED</h6>
    <h1 class="hp">EDC</h1>
    <p>#1 destination to find your unique festival outfit</p>
    <div class="sell-button">
    <%#= link_to "browse", articles_path, class: "content-button"%>
    </div>
  </div>
</div> -->


<!-- <div class="content-container-photo-4">
  <div class="content-text-photo">
    <h6>Get Inspired</h6>
    <h1 class="hp">Super Hero</h1>
    <p>#1 destination to find your unique festival outfit</p>
    <%= link_to "" , new_article_path  %>
  </div>
</div> -->

<div class="tags-container">
  <div class="tag-cards">
    <% @categories.each do |cat| %>
      <%= link_to articles_path(q: {category_name_eq: cat.name}) do %>
        <div class="tag-image" style="background-image: <%= cat.photo.attached? ? "url(#{url_for(cat.photo)})"  : "asset-url('article1.jpg')" %>">
           <p>
              <%= cat.name.pluralize %>
           </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="form-center-home">
<Begin Mailchimp Signup Form -->
<div class="suscribe-container">

<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{background:#fff; clear:left; font:14px Montserrat,Montserrat,sans-serif; }
  /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://herokuapp.us19.list-manage.com/subscribe/post?u=6b359760679e61f790db5a0c7&amp;id=7344d352ea" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <h2 class= "home-title">Wanna keep in touch?</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
  <label for="mce-FNAME">First Name </label>
  <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
  <label for="mce-LNAME">Last Name </label>
  <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group size1of2">
  <label for="mce-BIRTHDAY-month">Birthday </label>
  <div class="datefield">
    <span class="subfield monthfield"><input class="birthday " type="text" pattern="[0-9]*" value="" placeholder="MM" size="2" maxlength="2" name="BIRTHDAY[month]" id="mce-BIRTHDAY-month"></span> /
    <span class="subfield dayfield"><input class="birthday " type="text" pattern="[0-9]*" value="" placeholder="DD" size="2" maxlength="2" name="BIRTHDAY[day]" id="mce-BIRTHDAY-day"></span>
    <span class="small-meta nowrap">( mm / dd )</span>
  </div>
</div>  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_6b359760679e61f790db5a0c7_7344d352ea" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" style="background-color: #210461; font-weight: bold; width: 100%; padding-top: 11px; padding-bottom: 39px; letter-spacing: 1.5px; font-size: 18px;"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
</div>
</div>

<div class="footer-home">
  <p>© 2020 Fancier. All rights reserved.</p>
</div>

app/views/pages/listings.html.erb
<div class="background-profile">
  <%=  link_to new_article_path do %>
  <h1>+</h1>
  <% end %>

</div>
<div class="backround-user">
  <div class="profile-info">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar-xl", alt: "profile picture" %>
    <% else %>
      <%= image_tag "avatar.png", class: "avatar-xl" %>
    <% end %>
    <div class="add-margin">
    <h2>Order Dashboard</h2>
  </div>
  </div>
  <div class="dashboard-links">
    <div class="clothes listing-clothes">
      <a href="/dashboard">my purchases</a>
    </div>
      <div class="clothes">
      <a href="/listings">my listings</a>
    </div>
  </div>
</div>

<div class="order-container">
  <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        Sort by <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "All", listings_path, class: 'dropdown-link' %></li>
        <li class="divider"></li>
        <li><%= link_to "Pending", listings_path(state: :pending), class: 'dropdown-link' %></li>
        <li><%= link_to "Sold", listings_path(state: :paid), class: 'dropdown-link' %></li>
        <li><%= link_to "Shipped", listings_path(state: :shipped), class: 'dropdown-link' %></li>
        <li><%= link_to "Delivered", listings_path(state: :delivered), class: 'dropdown-link' %></li>
        <li><%= link_to "Cancelled", listings_path(state: :cancelled), class: 'dropdown-link' %></li>
      </ul>
    </div>

  <div class="order-section">
    <div class="orders">
      <% @listings.each do |article| %>
        <div class="d-flex border-order">
          <% if article.photos.first.nil?  %>
            <div class="order-photo" style="background-image:url(<%= image_path 'default-article.png' %>);">
            </div>
          <% else  %>
          <%= link_to article_path(article) do %>
            <div class="order-photo" style="background-image:url(<%= cl_image_path article.photos.first.key %>);">
            </div>
            <% end %>
          <% end %>
          <div class="order-info">

            <h2><%= article.name.capitalize %></h2>
            <h3>SIZE: <%= article.size %></h3>
            <h4><%= humanized_money_with_symbol article.price %></h4>
            <% if article.active_order.nil? %>
            <p class= "color-change-state">unsold</p>

            <% elsif article.active_order&.state == "paid" %>
            <% else %>
            <p><%= article.active_order&.state%></p>
            <% end %>
            <% if article.active_orders? && article.active_order&.state == 'paid' %>
            <div class="margin-button">
            <%= link_to " Mark as shipped", sellers_order_path(article.active_order), method: :patch, class: 'received' %>
            </div>

            <div class="d-flex photo-change margin-top-dash mt-20">
              <% if article.active_order.user.photo.attached? %>
                <%= cl_image_tag article.active_order.user.photo.key, class: "avatar-xsmall" %>

              <% else %>
                <%= image_tag "avatar.png", class: "avatar-xsmall" %>
              <% end %>
              <h4 class="" style= "font-weight: 400; "><%=  article.active_order.user&.name %> has purchased this item!</h4>
            </div>




            <% end %>
          </div>
        </div>
        <div class="total-section justify-content-between">
          <div class="subtotal">SUBTOTAL</div>
          <div class="price"><%= humanized_money_with_symbol article.price %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>